### ISSUE TITLE
Question about random photo pick

### ISSUE THREAD

**Issue by zettam** [iangreenleaf/node-tumblrbot#1]
What is the logic behind the random photo pick?

if I had 2 photo posts in total 100000 posts, would it still be able to return me a random photo?
if so, how?

thank you.

**Comment by iangreenleaf** [comment]
That should work, yes. Tumblr provides the total number of posts of a given type, and we take a random number within that range and make a request using that number as the offset (i.e. asking Tumblr to return us the post at that position). So it should work regardless of the number of posts available.

**Comment by zettam** [comment]
Thank you very much!
